#### Introduction

##### NumPy (Numeric Python" ou "Numerical Python) est l’un des packages fondamentaux pour tout ce qui concerne les traitements scientifiques dans Python. Il contient des fonctionnalités dédiées aux tableaux multidimensionnels, des fonctions mathématiques de haut niveau, comme les opérations d’algèbre linéaire

#### Lorsque vous téléchargez anaconda, de nombreux packages sont déjà installés pour vous, il vous suffit de l'importer.

In [3]:
#Pour voir la liste des packages qui sont installés

In [4]:
conda list

# packages in environment at /home/gobi/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39h06a4308_0  
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2021.11                  py39_0  
anaconda-client           1.9.0            py39h06a4308_0  
anaconda-navigator        2.1.1                    py39_0  
anaconda-project          0.10.1             pyhd3eb1b0_0  
anyio                     2.2.0            py39h06a4308_1  
appdirs                   1.4.4              pyhd3eb1b0_0  
argh                      0.26.2           py39h06a4308_0  
argon2-cffi               20.1.0           py39h27cfd23_1  
arrow                     0.13.1           py39h06a4308_0  
asn1crypto                1.4.0                      py_0  
astroid                   2.6.6         

In [5]:
import numpy as np
# %pip install numpy #Pour installer un package qui n'existe pas

In [6]:
#Version de numpy
np.__version__

'1.20.3'

#### 1er exemple
Notre premier exemple simple de Numpy traite des températures.

In [7]:
cvalues = [20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]


In [8]:
print(cvalues)

[20.1, 20.8, 21.9, 22.5, 22.7, 22.3, 21.8, 21.2, 20.9, 20.1]


In [9]:
type(cvalues)

list

In [10]:
## Nous allons transformer notre liste "cvalues" en un tableau numpy unidimensionnel :
C = np.array(cvalues)
print(C)

[20.1 20.8 21.9 22.5 22.7 22.3 21.8 21.2 20.9 20.1]


In [11]:
type(C)

numpy.ndarray

In [12]:
#Supposons que nous voulions transformer les valeurs en degrés Fahrenheit. 
#Ceci est très facile à réaliser avec un tableau numpy
print(C * 9 / 5 + 32)

[68.18 69.44 71.42 72.5  72.86 72.14 71.24 70.16 69.62 68.18]


In [13]:
#Par rapport à cela, la solution pour notre liste Python semble maladroite et plutot compliqué
fvalues = [ x*9/5 + 32 for x in cvalues]
print(fvalues)

[68.18, 69.44, 71.42, 72.5, 72.86, 72.14, 71.24000000000001, 70.16, 69.62, 68.18]


In [14]:
#Vous pouvez créer votre propre tableau numpy et définir le type de données des éléments
a = np.array([24.8, 12.9, 57.6], np.double)
print(a)

[24.8 12.9 57.6]


Autres types de données
https://numpy.org/doc/stable/user/basics.types.html

----------------------------------------------------------------------------------------------
CRÉATION DE TABLEAUX AVEC DES VALEURS RÉGULIÈREMENT ESPACÉES
ARANGE
La syntaxe de arange :
arange([start,] stop[, step], [, dtype=None])

In [15]:
a = np.arange(1, 11)
print(a)
x = range(1, 11)
print(x) # x est un itérateur
print(list(x))

[ 1  2  3  4  5  6  7  8  9 10]
range(1, 11)
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [16]:
type(a)

numpy.ndarray

In [17]:
y = np.arange(0.5, 10.4, 0.8) # Avec une etape de 0.8
print(y)

[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [18]:
z = np.arange(0.5, 10.4, 0.8, int) # En ajoutant le type de donnees
print(z)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
#Vous pouvez utiliser reshape pour modifier les dimensions/la forme de votre tableau numpy
b = a.reshape(5,2) #2 lignes, 5 columns
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [21]:
type(b)

numpy.ndarray

In [58]:
a.shape

(5,)

In [23]:

c = a.reshape(1,-1) # Le -1 signifie trouver le nombre correspondant de lignes avec une colonne
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [24]:

c = a.reshape(1,-1) # Le -1 signifie trouver le nombre correspondant de lignes avec une colonne
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [25]:
c.shape # 10 lignes, 1 colonne

(1, 10)

In [26]:
np.ndim(a)

1

--------------------------------------------------------------------------------------
Dimensions du tableau

In [27]:
# TABLEAUX ZÉRO-DIMENSIONNELS DANS NUMPY
import numpy as np
x = np.array(43)
print("x: ", x)
print("The type of x: ", type(x))
print("The dimension of x:", np.ndim(x))

x:  43
The type of x:  <class 'numpy.ndarray'>
The dimension of x: 0


In [28]:
#TABLEAUX UNIDIMENSIONNELS
V = np.array([3.4, 6.9, 99.8, 12.8], dtype=np.int8)
print("V: ", V)
print("Type of V: ", V.dtype)
print("Dimension of V: ", np.ndim(V))

V:  [ 3  6 99 12]
Type of V:  int8
Dimension of V:  1


In [29]:
#TABLEAUX BIDIMENSIONNELS ET MULTIDIMENSIONNELS
A = np.array([[3.4, 8.7, 9.9]])
print(A)
print("Dimension", A.ndim)


[[3.4 8.7 9.9]]
Dimension 2


In [30]:
A.shape

(1, 3)

In [31]:
B = np.array([[[111, 112], [121, 122]],
[[211, 212], [221, 222]],
[[311, 312], [321, 322]]])
print(B)
print("Dimension", B.ndim)

[[[111 112]
  [121 122]]

 [[211 212]
  [221 222]]

 [[311 312]
  [321 322]]]
Dimension 3


In [32]:
#FORME D'UN TABLEAU
B.shape

(3, 2, 2)

--------------------------------------------------------------------------------------------
INDEXATION ET TRANCHEMENT

In [33]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
# print le premier element
print(F)
print(F[0])
# print le dernier element
print(F[-1])


[ 1  1  2  3  5  8 13 21]
1
21


In [34]:
A = np.array([[3.4, 8.7, 9.9],
[1.1, -7.8, -0.7],
[4.1, 12.3, 4.8]])
print(A)
print(A[1][0]) #2eme ligne et premiere colonne
#oubien
print(A[1,0])


[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]]
1.1
1.1


In [35]:
#INDEXAGE
C = np.array([123,188,190,99,77,88,100])
A = np.array([4,  7,  2,  8, 6, 9, 5])
R = C[A>5] # On veut les valeurs de C où A est inférieur ou égal à 5. C et A doivent avoir la même longueur
print(R)
print(type(R))

[188  99  77  88]
<class 'numpy.ndarray'>


In [36]:
#INDEXATION AVEC UN TABLEAU D'ENTIERS
C[[0, 2, 3, 1, 4, 1]]

array([123, 190,  99, 188,  77, 188])

In [37]:
#TRANCHEMENT
#S[start:stop:step]
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(S[2:5])
print(S[:4])
print(S[6:])

[2 3 4]
[0 1 2 3]
[6 7 8 9]


In [38]:
#Pour acceder a tous:
print(S[:])


[0 1 2 3 4 5 6 7 8 9]


------------------------------------------------------------------------------------------
EXERCICES
Extrait du tableau np.array([3,4,6,10,24,89,45,43,46,99,100]) avec booléen masquant tout le nombre
• qui ne sont pas divisibles par 3
• qui sont divisibles par 5
• qui sont divisibles par 3 et 5
• qui sont divisibles par 3 et fixez-les à 42


-------------------------------------------------------------------------------------------------------
CRÉATION DE TABLEAUX AVEC DES UNS, DES ZÉROS ET DES VIDE

In [39]:
import numpy as np
E = np.ones((2,3))
print(E)
F = np.ones((3,4),dtype=np.double)
print(F)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [40]:
Z = np.zeros((5,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
T = np.empty((2, 4))
print(T)

[[4.94e-324 4.94e-324 9.88e-324 1.48e-323]
 [2.47e-323 3.95e-323 6.42e-323 1.04e-322]]


-----------------------------------------------------------------------------------------------
EXERCICES:
1) Créez un tableau unidimensionnel arbitraire appelé "v".
2) Créez un nouveau tableau composé des indices impairs du tableau "v" créé précédemment.
3) Créez un nouveau tableau dans l'ordre inverse de v.
4) Quelle sera la sortie du code suivant :
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
imprimer(a[1])
5) Créez un tableau à deux dimensions appelé "m".
6) Créez un nouveau tableau à partir de m, dans lequel les éléments de chaque ligne sont dans l'ordre inverse.
7) Un autre, où les rangées sont dans l'ordre inverse.
8) Créez un tableau à partir de m, où les colonnes et les lignes sont dans l'ordre inverse.
9) Coupe de la première et de la dernière rangée et de la première et de la dernière colonne.
-------------------------------------------------------------------------------------------------

OPÉRATIONS NUMÉRIQUES SUR NUMPY TABLEAUX

In [42]:
lst = [2,3, 7.9, 3.3, 6.9, 0.11, 10.3, 12.9]
v = np.array(lst)
v = v + 2
print(v)

[ 4.    5.    9.9   5.3   8.9   2.11 12.3  14.9 ]


In [43]:
print(v ** 2) # V au carré 

[ 16.      25.      98.01    28.09    79.21     4.4521 151.29   222.01  ]


In [44]:
# Si on utilisait des listes
res = [ val + 2 for val in lst]
print(res)

[4, 5, 9.9, 5.3, 8.9, 2.11, 12.3, 14.9]


MULTIPLICATION MATRICIELLE

In [45]:
A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
B = np.ones((3,3))
print("A \n", A)
print("B \n", B)

A 
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
B 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [46]:
np.dot(A, B)

array([[36., 36., 36.],
       [66., 66., 66.],
       [96., 96., 96.]])

In [47]:
# Vous pouvez accomplir la même chose en utilisant @
A@B

array([[36., 36., 36.],
       [66., 66., 66.],
       [96., 96., 96.]])

-------------------------------------------------------------------------------------
Opérations utiles

In [48]:
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [49]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
# Transposer
A.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [51]:
# enchaîner
CON = np.concatenate((A,B),axis=1) # Pour enchainer vers les colonnes, on met axis=1
CON

array([[11., 12., 13.,  1.,  1.,  1.],
       [21., 22., 23.,  1.,  1.,  1.],
       [31., 32., 33.,  1.,  1.,  1.]])

In [52]:
# EMPILAGE DE VECTEURS
A = np.array([3, 4, 5])
B = np.array([1,9,0])
print(A)
print(B)
print(np.row_stack((A, B))) # enchaîner par ligne
print(np.column_stack((A, B))) #enchaîner par colonne
np.shape(A)

[3 4 5]
[1 9 0]
[[3 4 5]
 [1 9 0]]
[[3 1]
 [4 9]
 [5 0]]


(3,)

In [53]:
# Aplatir et remodeler les tableaux: flatten() , ravel()
A = np.array([[[ 0, 1],
[ 2, 3],
[ 4, 5],
[ 6, 7]],
[[ 8, 9],
[10, 11],
[12, 13],
[14, 15]],
[[16, 17],
[18, 19],
[20, 21],
[22, 23]]])

Flattened_X = A.flatten()
print(A)
print(Flattened_X)
print(A.ravel())


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [54]:
# Reshape
X = np.array(range(24))
print("X\n", X)
Y = X.reshape((3,4,2))
print("X\n", Y)

X
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
X
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [55]:
#NOMBRES ALÉATOIRES, Random Numbers
np.random.randint(1, 10, size=20) # NOMBRES ALÉATOIRES entre 1 et 10

array([2, 6, 4, 1, 4, 1, 5, 5, 2, 4, 4, 6, 2, 8, 4, 1, 7, 1, 4, 5])

In [56]:
# NONZERO (PAS ZERO) AND WHERE (OÙ)
C = np.array([123,188,0,99,0,88,100])
print(C[C.nonzero()])
print(C[C != 0])

[123 188  99  88 100]
[123 188  99  88 100]


##### Il y a beaucoup plus que Numpy peut faire, mais cela devrait être bon pour une introduction à Numpy. Plus d'informations sur Numpy peuvent être trouvées sur la documentation ici:https://numpy.org/doc/stable/index.html

### QUESTIONS